# Generated by Django 5.1.1 on 2024-12-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cqt_app', '0006_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='QR_string',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='reason',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='reporting',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='start',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='day_out',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='reason',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
