# Generated by Django 5.1.1 on 2024-11-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cqt_app', '0007_attendance_qr_string_attendance_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-12-26 12:30'),
            preserve_default=False,
        ),
    ]
